### PR TITLE
Shivanshu

### PR DESCRIPTION
**Pull request by shivanshu1234**
### DVM Assignment: OOP
**Fruity: The Game** is the game that I have come up with for this assignment.
Please read 'README.md' before playing it.
Any suggestion/advice would be appreciated.

Thanks,
Shivanshu.

### CODE REVIEW

**Comment by Hypro999** [comment]
Please put these files in the right folder, make a sub-directory with your name in the OOP_101 directory. Then put these files there as others will also be uploading their code.

**Comment by Hypro999** [comment]
I'll have to do a full blown, in-depth review of your game tomorrow, but so far I like what I'm seeing. Hang in there!

**Comment by Hypro999** [comment]
_First off, I have to that I'm pretty impressed by this code.
It's well beyond beginner's level code._

### What Don't Like:
1. Your usage of global variables. Global variables should be avoided as much as possible to make your code more integratable with other people's code (I.E. when it is imported).

### What I Like:
1. Timely submission.
2. Usage of the third party library Openpyxl along with python's re module.
3. The game itself, despite being a simple number guessing game was enjoyable. So no issues with creativity. It's implementation is also on mark.
4. Sufficient usage of OOP. 
5. Pretty bug free. Couldn't find any bugs.
6. One of your classes inherited from python's built in list class. You doing this really shocked me. It's an advanced move.
7. Overall, seems pretty good especially for a first submission.

### Advice:
1. use the if \__name\__ == "\__main__" syntax for the execution part of your code. Maybe even a game engine kind of class. A game engine would have been pretty good for your code.

### Summary:
Excellent work!

**Comment by shivanshu1234** [comment]
I'll surely look into your suggestions. Thank you!

**Pull request merged**
