### PR TITLE
Abhinav

### PR DESCRIPTION
**Pull request by abhinav824**
The Game is ready :smile :+1:

### CODE REVIEW

**Comment by Hypro999** [comment]
Move your directory into OOP_101/

**Comment by Hypro999** [comment]
### What I Don't Like:
1. If a user dies, they should be able to replay from that point instead of from the very beginning.

### What I Like:
1. Creativity and Efforts put into making a complete game.
2. How well structured your code is.
3. Passing the name of the next room as the returned argument of the previous room.
4. Proper usage of OOP. You've implemented inheritance pretty well in a way, and implemented an abstract class (Scene). Good job, you did what I was looking for.

### Advice:
1. When the user enters a spell, if it's not on the list of spells (e.g. is misspelled or something), then let the user know that it's not a spell instead of sending them to their death.
2. Imperio isn't on the original list. Add it.
3. Use the if \__name\__ == "\__main__" syntax.

### Summary:
This is really good first submission. You've achieved the learning outcome. Keep it up.

**Comment by abhinav824** [comment]
I showed this game to my friend he aalso told the same that if a person dies he should be able to replay from that point only..... i'll try to do that in upcoming days..
I'll move the directory in correct place and add imperio to the main list.
actually i also thought about a that when the user entered a miss spelled spell it should show and error but in the movie when someone miss-spelled a spell, the spell didn't worked, so i sent him to death.
so i will add a message telling the user to renter the spell if it is not in the list.

**Comment by Hypro999** [comment]
for now just move the directory so that I can merge this PR.

**Comment by abhinav824** [comment]
Final Commit is ready to be pulled..

**Comment by Hypro999** [comment]
Alright, looks good. Congratulations on finishing your task!

**Pull request merged**
