### PR TITLE
Completed the basic application framework. However, Some features hav…

### PR DESCRIPTION
**Pull request by theweblover007**
…e been extremely scaled down due to the extra complexity that came with them. The code right now is not well commented which will be done in the later commits. 
May you understand my code, because I don't. :D

### CODE REVIEW

**Comment by Hypro999** [comment]
One bit of advice, try separating the logic from the I/O portions of the code. This isn't something that you are expected to know beforehand but real world OOP based software has their classes and logic separate from the driver part of the code which will handle communication with the user. An example of what I mean is that the constructor to a class shouldn't be doing ANY IO with the user IMO. Try restructuring this code.

**Comment by Hypro999** [comment]
Also, I suggest you try to add more to this project before I pull it. Try taking your time with Object-Oriented design process (any ad-hoc design as you please, no need for any thing fancy or professional, but show a bit more structure in your approach). Nice efforts though so far.

One more thing, read up on PEP 8 (no need for the line length limitations, but read up on the blank spaces rule at least).

Lastly, as mentioned in the above comment, don't forget to separate the driver part of your code from the  logic part. (this may not be the best example or anything but it should be a good enough reference: https://github.com/Hypro999/YMC/blob/master/YMC.py)

**Comment by Hypro999** [comment]
I'll do a more in-depth review tomorrow, but so far, I like your use of lambda functions for simpler code but there seem like a lot of changes are needed especially since the idea you originally pitched was a really good one (raised our expectations there quite a bit), we'll talk about them soon. Also, *do* implement a data store, if needed I'll provide continuous advice here.

**Comment by theweblover007** [comment]
> I'll do a more in-depth review tomorrow, but so far, I like your use of lambda functions for simpler code but there seem like a lot of changes are needed especially since the idea you originally pitched was a really good one (raised our expectations there quite a bit), we'll talk about them soon. Also, _do_ implement a data store, if needed I'll provide continuous advice here.

What do you mean by datastore, can you please clarify?

**Comment by theweblover007** [comment]
And by separating I/O , you mean should i not at all read and write in the classes or should i not read and write in the init constructor ?

**Comment by Hypro999** [comment]
Meet me today and we shall discuss it. By datastore, I mean, store the data of buyers and sellers in a file or database. 
The magic methods like __init__ should not be asking for user input but the other methods could.

**Comment by theweblover007** [comment]
Okay thanks, I will be spending most of my day today with this project. I am reading up on storing and retriving data in json as well as a python gui library

**Comment by Hypro999** [comment]
GUI is not at all needed right now, you can begin working with a GUI once you begin learning Django. Trust me, it's much better this way. Just make a better CLI and implement some way to store your data.

**Comment by Hypro999** [comment]
Progress????

**Comment by theweblover007** [comment]
Please check the latest commit.
\

**Comment by Hypro999** [comment]
Congratulations on finishing your OOP Assignment!

**Pull request merged**
